spring:
  application:
    name: rb-consumer
  rabbitmq:
    host: 101.43.215.185
    port: 5672
    username: spring_cloud_demo
    password: 123456
    virtual-host: /cloud
    listener:
      simple:
        prefetch: 1